"""Offline German→English translator for G-BA pharmaceutical/HTA texts.

Uses a comprehensive phrase-level + word-level dictionary tailored to
the formulaic language of G-BA AMNOG benefit assessment decisions.
No external API or network access required.
"""

import re

# ── Phrase-level dictionary (matched first, longest-match priority) ────

_PHRASES: dict[str, str] = {
    # Common indication patterns
    "ist angezeigt zur Behandlung": "is indicated for the treatment",
    "ist indiziert zur Behandlung": "is indicated for the treatment",
    "ist als Monotherapie angezeigt zur Behandlung": "is indicated as monotherapy for the treatment",
    "ist als Monotherapie zur Behandlung": "is indicated as monotherapy for the treatment",
    "ist als Monotherapie indiziert zur Behandlung": "is indicated as monotherapy for the treatment",
    "wird angewendet zur Behandlung": "is used for the treatment",
    "wird angewendet bei": "is used in",
    "wird angewendet für die Behandlung": "is used for the treatment",
    "ist angezeigt für die Behandlung": "is indicated for the treatment",
    "ist angezeigt als": "is indicated as",
    "ist angezeigt bei": "is indicated for",
    "ist angezeigt zur": "is indicated for",
    "ist indiziert als": "is indicated as",
    "ist indiziert bei": "is indicated for",
    "ist indiziert zur": "is indicated for",
    "ist indiziert für": "is indicated for",
    "ist angezeigt für": "is indicated for",
    "wird angewendet als": "is used as",
    "wird angewendet in Kombination mit": "is used in combination with",
    "wird angewendet in": "is used in",

    # Combination therapy
    "in Kombination mit": "in combination with",
    "als Monotherapie": "as monotherapy",
    "als Kombinationstherapie": "as combination therapy",
    "als Dreifach-Kombinationstherapie": "as triple combination therapy",
    "Kombination mit": "combination with",
    "Monotherapie oder in Kombination mit": "monotherapy or in combination with",
    "als Add-on-Therapie": "as add-on therapy",
    "als Add-on-Erhaltungstherapie": "as add-on maintenance therapy",
    "als Zusatztherapie": "as adjunctive therapy",
    "als Erhaltungstherapie": "as maintenance therapy",
    "als Erhaltungsmonotherapie": "as maintenance monotherapy",
    "als Zweitlinientherapie": "as second-line therapy",
    "als Erstlinientherapie": "as first-line therapy",
    "als Erstlinienbehandlung": "as first-line treatment",

    # Patient populations
    "erwachsener Patienten": "of adult patients",
    "erwachsenen Patienten": "adult patients",
    "erwachsene Patienten": "adult patients",
    "Erwachsene Patienten": "Adult patients",
    "Erwachsenen Patienten": "Adult patients",
    "pädiatrischen Patienten": "paediatric patients",
    "pädiatrische Patienten": "paediatric patients",
    "Patientinnen und Patienten": "patients",
    "bei Erwachsenen": "in adults",
    "bei Erwachsene": "in adults",
    "bei Kindern und Jugendlichen": "in children and adolescents",
    "bei Kindern": "in children",
    "bei Jugendlichen": "in adolescents",
    "Kinder und Jugendliche": "children and adolescents",
    "Kindern und Jugendlichen": "children and adolescents",
    "bei Frauen": "in women",
    "bei Männern": "in men",
    "bei Neugeborenen": "in neonates",
    "bei Säuglingen": "in infants",

    # Age/weight qualifiers
    "im Alter von": "aged",
    "ab einem Alter von": "from the age of",
    "mit einem Körpergewicht von": "with a body weight of",
    "mit einem Körpergewicht ab": "with a body weight of at least",
    "Jahren und älter": "years and older",

    # Disease states
    "nicht-resezierbarem oder metastasiertem": "unresectable or metastatic",
    "lokal fortgeschrittenem oder metastasiertem": "locally advanced or metastatic",
    "lokal fortgeschrittenen oder metastasierten": "locally advanced or metastatic",
    "lokal fortgeschrittenem": "locally advanced",
    "lokal fortgeschrittenen": "locally advanced",
    "nicht-kleinzelligem Lungenkarzinom": "non-small cell lung cancer",
    "nicht-kleinzelligen Lungenkarzinom": "non-small cell lung cancer",
    "nicht-kleinzelliges Lungenkarzinom": "non-small cell lung cancer",
    "nicht-resezierbarem": "unresectable",
    "nicht resezierbarem": "unresectable",
    "rezidiviertem oder refraktärem": "relapsed or refractory",
    "rezidivierender oder refraktärer": "relapsing or refractory",
    "rezidiviertem und refraktärem": "relapsed and refractory",
    "rezidivierendem oder refraktärem": "relapsing or refractory",
    "schubförmig-remittierender Multipler Sklerose": "relapsing-remitting multiple sclerosis",
    "schubförmiger Multipler Sklerose": "relapsing multiple sclerosis",
    "Multipler Sklerose": "multiple sclerosis",
    "Diabetes mellitus": "diabetes mellitus",
    "Diabetes mellitus Typ 2": "type 2 diabetes mellitus",
    "Diabetes mellitus Typ 1": "type 1 diabetes mellitus",
    "Typ-2-Diabetes mellitus": "type 2 diabetes mellitus",
    "Typ-2-Diabetes": "type 2 diabetes",
    "Typ-1-Diabetes": "type 1 diabetes",
    "rheumatoider Arthritis": "rheumatoid arthritis",
    "rheumatoide Arthritis": "rheumatoid arthritis",
    "Morbus Crohn": "Crohn's disease",
    "Colitis ulcerosa": "ulcerative colitis",
    "systemischem Lupus erythematodes": "systemic lupus erythematosus",
    "atopischer Dermatitis": "atopic dermatitis",
    "atopische Dermatitis": "atopic dermatitis",
    "chronischer lymphatischer Leukämie": "chronic lymphocytic leukaemia",
    "chronische lymphatische Leukämie": "chronic lymphocytic leukaemia",
    "akuter lymphatischer Leukämie": "acute lymphoblastic leukaemia",
    "akute lymphatische Leukämie": "acute lymphoblastic leukaemia",
    "akuter myeloischer Leukämie": "acute myeloid leukaemia",
    "akute myeloische Leukämie": "acute myeloid leukaemia",
    "chronischer myeloischer Leukämie": "chronic myeloid leukaemia",
    "chronische myeloische Leukämie": "chronic myeloid leukaemia",
    "myelodysplastischem Syndrom": "myelodysplastic syndrome",
    "myelodysplastischen Syndromen": "myelodysplastic syndromes",
    "multiplem Myelom": "multiple myeloma",
    "multiples Myelom": "multiple myeloma",
    "multiplen Myelom": "multiple myeloma",
    "Hodgkin-Lymphom": "Hodgkin lymphoma",
    "Non-Hodgkin-Lymphom": "non-Hodgkin lymphoma",
    "Mantelzelllymphom": "mantle cell lymphoma",
    "follikulärem Lymphom": "follicular lymphoma",
    "follikuläres Lymphom": "follicular lymphoma",
    "diffusem großzelligem B-Zell-Lymphom": "diffuse large B-cell lymphoma",
    "Nierenzellkarzinom": "renal cell carcinoma",
    "Hepatozellulärem Karzinom": "hepatocellular carcinoma",
    "hepatozellulärem Karzinom": "hepatocellular carcinoma",
    "Prostatakarzinom": "prostate cancer",
    "Mammakarzinom": "breast cancer",
    "Ovarialkarzinom": "ovarian cancer",
    "Endometriumkarzinom": "endometrial cancer",
    "Zervixkarzinom": "cervical cancer",
    "Pankreaskarzinom": "pancreatic cancer",
    "kolorektalem Karzinom": "colorectal cancer",
    "kolorektalen Karzinom": "colorectal cancer",
    "kolorektales Karzinom": "colorectal cancer",
    "Plattenepithelkarzinom": "squamous cell carcinoma",
    "Urothelkarzinom": "urothelial carcinoma",
    "kutanen Plattenepithelkarzinom": "cutaneous squamous cell carcinoma",
    "Schilddrüsenkarzinom": "thyroid carcinoma",
    "Magenkarzinom": "gastric carcinoma",
    "Cholangiokarzinom": "cholangiocarcinoma",
    "Bronchialkarzinom": "bronchial carcinoma",
    "Basalzellkarzinom": "basal cell carcinoma",
    "Merkelzellkarzinom": "Merkel cell carcinoma",
    "Pleuramesotheliom": "pleural mesothelioma",
    "Melanom": "melanoma",
    "Myelofibrose": "myelofibrosis",
    "Polycythaemia vera": "polycythaemia vera",
    "essentieller Thrombozythämie": "essential thrombocythaemia",
    "Psoriasis-Arthritis": "psoriatic arthritis",
    "Plaque-Psoriasis": "plaque psoriasis",
    "cystischer Fibrose": "cystic fibrosis",
    "zystischer Fibrose": "cystic fibrosis",
    "Mukoviszidose": "cystic fibrosis",
    "pulmonaler arterieller Hypertonie": "pulmonary arterial hypertension",
    "pulmonale arterielle Hypertonie": "pulmonary arterial hypertension",
    "idiopathischer Lungenfibrose": "idiopathic pulmonary fibrosis",
    "idiopathische Lungenfibrose": "idiopathic pulmonary fibrosis",
    "Epilepsie": "epilepsy",
    "Vorhofflimmern": "atrial fibrillation",
    "Herzinsuffizienz": "heart failure",
    "koronarer Herzkrankheit": "coronary heart disease",
    "chronisch obstruktiver Lungenerkrankung": "chronic obstructive pulmonary disease",
    "chronisch-obstruktiver Lungenerkrankung": "chronic obstructive pulmonary disease",
    "Asthma bronchiale": "bronchial asthma",
    "Hämophilie A": "haemophilia A",
    "Hämophilie B": "haemophilia B",
    "spinaler Muskelatrophie": "spinal muscular atrophy",
    "spinale Muskelatrophie": "spinal muscular atrophy",
    "amyotropher Lateralsklerose": "amyotrophic lateral sclerosis",
    "Parkinson-Krankheit": "Parkinson's disease",
    "Morbus Parkinson": "Parkinson's disease",
    "Alzheimer-Krankheit": "Alzheimer's disease",
    "Migräne": "migraine",
    "Schizophrenie": "schizophrenia",
    "bipolare Störung": "bipolar disorder",
    "bipolarer Störung": "bipolar disorder",
    "Depression": "depression",
    "Hepatitis C": "hepatitis C",
    "Hepatitis B": "hepatitis B",
    "HIV-1-Infektion": "HIV-1 infection",
    "HIV-Infektion": "HIV infection",
    "Clostridioides-difficile-Infektion": "Clostridioides difficile infection",
    "Tuberkulose": "tuberculosis",

    # Treatment lines / prior therapy
    "nach vorheriger Therapie": "after prior therapy",
    "nach Versagen der vorherigen Therapie": "after failure of prior therapy",
    "nach vorheriger Behandlung": "after prior treatment",
    "nach vorhergehender Behandlung": "after previous treatment",
    "nach mindestens einer": "after at least one",
    "nach mindestens zwei": "after at least two",
    "nach mindestens drei": "after at least three",
    "nach mindestens einer vorangegangenen Therapie": "after at least one prior therapy",
    "nach mindestens einer vorherigen": "after at least one prior",
    "vorangegangene Therapien": "prior therapies",
    "vorangegangene Therapie": "prior therapy",
    "vorangegangenen Therapien": "prior therapies",
    "vorangegangener Therapie": "prior therapy",
    "nach Progression": "after progression",
    "nach einer Chemotherapie": "after chemotherapy",
    "nach vorheriger Chemotherapie": "after prior chemotherapy",
    "nach platinbasierter Chemotherapie": "after platinum-based chemotherapy",
    "nach platinhaltiger Chemotherapie": "after platinum-containing chemotherapy",
    "nach Stammzelltransplantation": "after stem cell transplantation",
    "nach autologer Stammzelltransplantation": "after autologous stem cell transplantation",
    "nach allogener Stammzelltransplantation": "after allogeneic stem cell transplantation",
    "hämatopoetischer Stammzelltransplantation": "haematopoietic stem cell transplantation",

    # Qualifiers
    "als Ergänzung zu Diät und Bewegung": "as an adjunct to diet and exercise",
    "Ergänzung zu Diät und Bewegung": "adjunct to diet and exercise",
    "Diät und Bewegung": "diet and exercise",
    "nicht ausreichend kontrolliert": "not adequately controlled",
    "unzureichend kontrolliert": "inadequately controlled",
    "nicht ausreichend behandelt": "not adequately treated",
    "unzureichend behandelt": "inadequately treated",
    "nicht ausreichend eingestellt": "not adequately controlled",
    "nicht ausreichend angesprochen": "not adequately responded",
    "unzureichend angesprochen": "inadequately responded",
    "nicht angesprochen haben": "have not responded",
    "angesprochen haben": "have responded",
    "nicht vertragen": "do not tolerate",
    "die nicht vertragen": "who do not tolerate",
    "die nicht geeignet sind": "who are not eligible",
    "für die eine Behandlung mit": "for whom treatment with",
    "nicht in Frage kommt": "is not suitable",
    "nicht infrage kommt": "is not suitable",
    "nicht in Betracht kommt": "is not considered appropriate",
    "nicht infrage kommen": "are not suitable",
    "nicht in Frage kommen": "are not suitable",
    "in Frage kommt": "is suitable",
    "infrage kommt": "is suitable",
    "in Betracht kommt": "is considered appropriate",
    "geeignet sind": "are eligible",
    "geeignet ist": "is eligible",
    "nicht geeignet ist": "is not eligible",
    "nicht geeignet sind": "are not eligible",
    "eine kurative Operation": "curative surgery",
    "kurative Strahlentherapie": "curative radiotherapy",
    "kontraindiziert ist": "is contraindicated",
    "kontraindiziert sind": "are contraindicated",
    "intolerant gegenüber": "intolerant to",
    "resistent oder intolerant": "resistant or intolerant",
    "resistent gegenüber": "resistant to",
    "refraktär gegenüber": "refractory to",
    "nach Versagen von": "after failure of",
    "nicht mehr ansprechen": "no longer respond",
    "unverträglich sind": "are intolerant",
    "unverträglich ist": "is intolerant",

    # Status descriptors
    "positiver Tumorstatus": "positive tumour status",
    "positivem Tumorstatus": "positive tumour status",
    "negativer Tumorstatus": "negative tumour status",
    "negativem Tumorstatus": "negative tumour status",
    "als Erstlinientherapie": "as first-line therapy",
    "als Zweitlinientherapie": "as second-line therapy",
    "als Erstlinienbehandlung": "as first-line treatment",

    # Therapy-related
    "Supportive Care": "supportive care",
    "Best Supportive Care": "best supportive care",
    "patientenindividuelle Therapie": "patient-individualised therapy",
    "patientenindividuell optimierte Therapie": "patient-individually optimised therapy",
    "Eine patientenindividuelle Therapie": "A patient-individualised therapy",
    "unter Berücksichtigung": "taking into account",
    "unter Berücksichtigung des Allgemeinzustands": "taking into account the general condition",
    "ggf. von Vortherapien": "and, if applicable, prior therapies",
    "Vortherapien und von der Remissionsdauer nach initialer Therapie": "prior therapies and the duration of remission after initial therapy",
    "ärztlicher Maßgabe": "at physician's discretion",
    "unter ärztlicher Maßgabe": "at physician's discretion",
    "nach Maßgabe des Arztes": "at the physician's discretion",
    "zweckmäßige Vergleichstherapie": "appropriate comparator therapy",
    "Zweckmäßige Vergleichstherapie": "Appropriate comparator therapy",
    "blutzuckersenkenden Arzneimitteln": "blood glucose-lowering agents",
    "blutzuckersenkende Arzneimittel": "blood glucose-lowering agents",
    "blutzuckersenkender Therapie": "blood glucose-lowering therapy",

    # Surgery/procedures
    "vollständiger Resektion": "complete resection",
    "vollständige Resektion": "complete resection",
    "nach vollständiger Resektion": "after complete resection",
    "chirurgischer Resektion": "surgical resection",
    "adjuvante Behandlung": "adjuvant treatment",
    "adjuvante Therapie": "adjuvant therapy",
    "neoadjuvante Behandlung": "neoadjuvant treatment",
    "neoadjuvante Therapie": "neoadjuvant therapy",
    "Adjuvante Behandlung": "Adjuvant treatment",

    # Common endings / connectors
    "dieses Arzneimittel": "this medicinal product",
    "Dieses Arzneimittel": "This medicinal product",
    "ist ein Diagnostikum": "is a diagnostic agent",
    "Arzneimittel ist": "medicinal product is",

    # More disease context
    "des Magens": "of the stomach",
    "des gastroösophagealen Übergangs": "of the gastro-oesophageal junction",
    "gastroösophagealen Übergangs": "gastro-oesophageal junction",
    "des Ösophagus": "of the oesophagus",
    "der Schilddrüse": "of the thyroid",
    "der Lunge": "of the lung",
    "der Leber": "of the liver",
    "der Niere": "of the kidney",
    "des Darms": "of the intestine",
    "der Haut": "of the skin",
    "der Brust": "of the breast",
    "der Prostata": "of the prostate",

    # Relative clauses
    "die bereits": "who have already",
    "die zuvor": "who have previously",
    "die vorher": "who have previously",
    "die nicht": "who do not",
    "die für": "for whom",
    "die eine": "who have a",
    "die einen": "who have a",
    "die an": "who suffer from",
    "die auf": "who are on",
    "die unter": "who are under",
    "die nach": "who after",
    "bei denen": "in whom",
    "bei dem": "in which",
    "bei der": "in which",
    "für die": "for whom",

    # More therapy patterns
    "als Alternative zu": "as an alternative to",
    "im Vergleich zu": "compared to",
    "im Rahmen": "in the context of",
    "im Rahmen einer": "in the context of a",
    "anstelle von": "instead of",
    "Wahl des Arztes": "physician's choice",
    "nach Wahl des Arztes": "at physician's choice",
    "nach ärztlicher": "at physician's",
    "auf Basis von": "based on",
    "basierend auf": "based on",
    "im Hinblick auf": "with regard to",
    "mit Bezug auf": "with reference to",
    "nicht mehr ansprechen auf": "no longer respond to",

    # More adjective/adverb patterns
    "vormals": "formerly",
    "erstmals": "for the first time",
    "langfristig": "long-term",
    "kurzfristig": "short-term",
    "gleichzeitig": "simultaneously",
    "nachfolgend": "subsequently",
    "dauerhaft": "permanently",
    "zeitweise": "temporarily",
    "teilweise": "partially",
    "überwiegend": "predominantly",
    "häufig": "frequently",
    "gelegentlich": "occasionally",
    "regelmäßig": "regularly",
    "kontinuierlich": "continuously",
    "voraussichtlich": "expected",
    "wahrscheinlich": "likely",
    "möglicherweise": "possibly",
    "nachweislich": "demonstrably",
    "weiterhin": "furthermore",

    # Relative clause connectors (case-sensitive phrases)
    "die auf eine": "who have not responded to a",
    "die unter einer": "who are under a",

    # More disease names as phrases
    "ankylosierender Spondylitis": "ankylosing spondylitis",
    "ankylosierende Spondylitis": "ankylosing spondylitis",
    "Spondylitis ankylosans": "ankylosing spondylitis",
    "axiale Spondyloarthritis": "axial spondyloarthritis",
    "axialem Spondyloarthritis": "axial spondyloarthritis",
    "axialer Spondyloarthritis": "axial spondyloarthritis",
    "Morbus Bechterew": "Bechterew's disease",
    "zystische Fibrose": "cystic fibrosis",
    "Ewing-Sarkom": "Ewing sarcoma",
    "Weichteilsarkom": "soft tissue sarcoma",
    "Gastrointestinaler Stromatumor": "gastrointestinal stromal tumour",
    "gastrointestinaler Stromatumor": "gastrointestinal stromal tumour",
    "gastrointestinalen Stromatumoren": "gastrointestinal stromal tumours",
    "myeloproliferativer Neoplasien": "myeloproliferative neoplasms",
    "myeloproliferative Neoplasien": "myeloproliferative neoplasms",
    "venöse Thromboembolie": "venous thromboembolism",
    "venöser Thromboembolie": "venous thromboembolism",
    "tiefe Venenthrombose": "deep vein thrombosis",
    "tiefer Venenthrombose": "deep vein thrombosis",
    "Lungenembolie": "pulmonary embolism",
    "Vorhofflimmern": "atrial fibrillation",
    "nicht-valvulärem Vorhofflimmern": "non-valvular atrial fibrillation",
    "Herzinsuffizienz mit reduzierter Ejektionsfraktion": "heart failure with reduced ejection fraction",
    "Herzinsuffizienz mit erhaltener Ejektionsfraktion": "heart failure with preserved ejection fraction",
    "essentieller Thrombozythämie": "essential thrombocythaemia",
    "eosinophiler Ösophagitis": "eosinophilic oesophagitis",
    "eosinophile Ösophagitis": "eosinophilic oesophagitis",
    "Graft-versus-Host-Krankheit": "graft-versus-host disease",
    "Sichelzellkrankheit": "sickle cell disease",
    "Sichelzellanämie": "sickle cell anaemia",
    "Hämophilie A": "haemophilia A",
    "Hämophilie B": "haemophilia B",
    "von-Willebrand-Erkrankung": "von Willebrand disease",

    # More compound nouns
    "Leberzellkarzinom": "hepatocellular carcinoma",
    "Gallengangskarzinom": "bile duct carcinoma",
    "Adenokarzinom": "adenocarcinoma",
    "Adenokarzinoms": "adenocarcinoma",
    "Plattenepithelkarzinoms": "squamous cell carcinoma",
    "Lungenkarzinoms": "lung carcinoma",
    "Urothelkarzinoms": "urothelial carcinoma",
    "Nierenzellkarzinoms": "renal cell carcinoma",
    "Prostatakarzinoms": "prostate carcinoma",
    "Ovarialkarzinoms": "ovarian carcinoma",
    "Schilddrüsenkarzinoms": "thyroid carcinoma",

    # Organ-specific adjectives
    "pulmonaler": "pulmonary",
    "pulmonale": "pulmonary",
    "pulmonalem": "pulmonary",
    "pulmonalen": "pulmonary",
    "renaler": "renal",
    "renale": "renal",
    "renalem": "renal",
    "renalen": "renal",
    "hepatischer": "hepatic",
    "hepatische": "hepatic",
    "hepatischem": "hepatic",
    "hepatischen": "hepatic",
    "gastrointestinaler": "gastrointestinal",
    "gastrointestinale": "gastrointestinal",
    "gastrointestinalem": "gastrointestinal",
    "gastrointestinalen": "gastrointestinal",
    "kardiovaskulärer": "cardiovascular",
    "kardiovaskuläre": "cardiovascular",
    "kardiovaskulären": "cardiovascular",
    "hämatologischer": "haematological",
    "hämatologische": "haematological",
    "hämatologischen": "haematological",
    "hämatopoetischer": "haematopoietic",
    "hämatopoetische": "haematopoietic",
    "hämatopoetischen": "haematopoietic",
    "onkologischer": "oncological",
    "onkologische": "oncological",
    "onkologischen": "oncological",
    "neurologischer": "neurological",
    "neurologische": "neurological",
    "neurologischen": "neurological",
    "endokriner": "endocrine",
    "endokrine": "endocrine",
    "endokrinen": "endocrine",
    "immunologischer": "immunological",
    "immunologische": "immunological",
    "immunologischen": "immunological",
    "dermatologischer": "dermatological",
    "dermatologische": "dermatological",
    "dermatologischen": "dermatological",
    "ophthalmologischer": "ophthalmological",
    "ophthalmologische": "ophthalmological",
    "ophthalmologischen": "ophthalmological",
    "metabolischer": "metabolic",
    "metabolische": "metabolic",
    "metabolischen": "metabolic",
    "inflammatorischer": "inflammatory",
    "inflammatorische": "inflammatory",
    "inflammatorischen": "inflammatory",
    "autoimmune": "autoimmune",
    "autoimmuner": "autoimmune",
    "autoimmunologischer": "autoimmune",
    "periphere": "peripheral",
    "peripherer": "peripheral",
    "peripherem": "peripheral",
    "peripheren": "peripheral",
    "hämatologisch": "haematological",

    # "follicular" adjective forms
    "follikulärem": "follicular",
    "follikulären": "follicular",
    "follikulärer": "follicular",
    "follikuläre": "follicular",
    "follikuläres": "follicular",

    # Common therapy-related nouns
    "Linien": "lines",
    "Linie": "line",
    "Monat": "month",
    "Jahr": "year",
    "Kopien": "copies",
    "Kopie": "copy",
    "Viruslast": "viral load",
    "Aktivität": "activity",
    "Wirksamkeitsverlust": "loss of efficacy",
    "Splenomegalie": "splenomegaly",
    "Hepatomegalie": "hepatomegaly",
    "Aszites": "ascites",
    "Ödem": "oedema",
    "Ödeme": "oedemas",
    "Ikterus": "jaundice",
    "Alopezie": "alopecia",
    "Vitiligo": "vitiligo",
    "Urtikaria": "urticaria",
    "Angioödem": "angioedema",
    "Myalgie": "myalgia",
    "Arthralgie": "arthralgia",
    "Neuropathie": "neuropathy",
    "Retinopathie": "retinopathy",
    "Nephropathie": "nephropathy",
    "Kardiomyopathie": "cardiomyopathy",
    "Enzephalopathie": "encephalopathy",
    "Manifestation": "manifestation",
    "Manifestationen": "manifestations",
    "Stammzellen": "stem cells",
    "Stammzelle": "stem cell",
    "Formen": "forms",
    "Form": "form",

    # More adjective forms commonly remaining
    "aktivierenden": "activating",
    "aktivierende": "activating",
    "aktivierender": "activating",
    "assoziiert": "associated",
    "assoziierte": "associated",
    "assoziierten": "associated",
    "assoziierter": "associated",
    "assoziiertem": "associated",
    "späten": "late",
    "spätem": "late",
    "später": "late",
    "späte": "late",
    "frühen": "early",
    "früher": "early",
    "frühe": "early",
    "frühem": "early",
}

# ── Word-level dictionary ────────────────────────────────────────────

_WORDS: dict[str, str] = {
    # Articles / pronouns / prepositions
    "der": "the",
    "die": "the",
    "das": "the",
    "des": "of the",
    "dem": "the",
    "den": "the",
    "ein": "a",
    "eine": "a",
    "eines": "of a",
    "einer": "of a",
    "einem": "a",
    "einen": "a",
    "mit": "with",
    "bei": "in",
    "zur": "for",
    "zum": "for",
    "von": "of",
    "für": "for",
    "und": "and",
    "oder": "or",
    "und/oder": "and/or",
    "als": "as",
    "nach": "after",
    "in": "in",
    "auf": "on",
    "zu": "to",
    "aus": "from",
    "durch": "through",
    "über": "over",
    "unter": "under",
    "vor": "before",
    "ab": "from",
    "bis": "to",
    "seit": "since",
    "ohne": "without",
    "gegen": "against",
    "zwischen": "between",
    "während": "during",
    "trotz": "despite",
    "gemäß": "according to",
    "wegen": "because of",
    "diese": "these",
    "dieser": "this",
    "diesem": "this",
    "diesen": "these",
    "ihre": "their",
    "ihren": "their",
    "ihrem": "their",
    "deren": "whose",
    "denen": "whom",
    "welche": "which",
    "sowie": "as well as",
    "bzw": "or",
    "ggf": "if applicable",
    "sog": "so-called",
    "z.B.": "e.g.",
    "d.h.": "i.e.",
    "d. h.": "i.e.",
    "nur": "only",
    "auch": "also",
    "noch": "still",
    "nicht": "not",
    "keine": "no",
    "keinen": "no",
    "keiner": "no",
    "kein": "no",
    "bereits": "already",
    "zuvor": "previously",
    "dabei": "thereby",
    "jeweils": "respectively",
    "mindestens": "at least",
    "mehr": "more",
    "weniger": "less",
    "jeder": "each",
    "alle": "all",
    "anderen": "other",
    "andere": "other",
    "anderer": "other",
    "anderem": "other",
    "einschließlich": "including",
    "ausschließlich": "exclusively",
    "insbesondere": "in particular",
    "zusätzlich": "additionally",
    "gleichzeitig": "simultaneously",
    "entsprechend": "corresponding",
    "aufgrund": "due to",
    "wenn": "if",
    "sofern": "provided that",
    "soweit": "insofar as",
    "da": "since",
    "obwohl": "although",
    "dass": "that",
    "sobald": "as soon as",
    "dennoch": "nevertheless",
    "jedoch": "however",
    "allerdings": "however",
    "ebenso": "likewise",
    "außer": "except",
    "außerdem": "furthermore",
    "darunter": "including",
    "davon": "thereof",
    "dazu": "in addition",
    "hierzu": "for this",
    "hierfür": "for this",
    "hierbei": "hereby",
    "gegenüber": "compared to",
    "innerhalb": "within",
    "oberhalb": "above",
    "unterhalb": "below",
    "hinsichtlich": "regarding",
    "bezüglich": "regarding",
    "anhand": "based on",
    "mittels": "by means of",
    "laut": "according to",
    "statt": "instead of",
    "anstelle": "instead of",

    # Numbers
    "zwei": "two",
    "drei": "three",
    "vier": "four",
    "fünf": "five",
    "sechs": "six",
    "sieben": "seven",
    "acht": "eight",
    "neun": "nine",
    "zehn": "ten",
    "elf": "eleven",
    "zwölf": "twelve",
    "erste": "first",
    "ersten": "first",
    "erster": "first",
    "zweite": "second",
    "zweiten": "second",
    "zweiter": "second",
    "dritte": "third",
    "dritten": "third",
    "dritter": "third",

    # Verbs
    "ist": "is",
    "sind": "are",
    "wird": "is",
    "werden": "are",
    "wurde": "was",
    "wurden": "were",
    "hat": "has",
    "haben": "have",
    "hatte": "had",
    "kann": "can",
    "können": "can",
    "soll": "should",
    "sollte": "should",
    "muss": "must",
    "darf": "may",
    "angezeigt": "indicated",
    "indiziert": "indicated",
    "angewendet": "used",
    "behandelt": "treated",
    "erhalten": "received",
    "vertragen": "tolerated",
    "geeignet": "suitable",
    "vorbehandelt": "pretreated",
    "vorbehandelte": "pretreated",
    "vorbehandelten": "pretreated",
    "angesprochen": "responded",
    "fortgeschritten": "advanced",
    "fortgeschrittener": "advanced",
    "fortgeschrittenem": "advanced",
    "fortgeschrittenen": "advanced",
    "fortgeschrittene": "advanced",
    "empfohlen": "recommended",
    "zugelassen": "authorised",
    "wirksam": "effective",
    "bestätigt": "confirmed",
    "diagnostiziert": "diagnosed",
    "diagnostiziertem": "diagnosed",
    "diagnostizierten": "diagnosed",
    "diagnostizierter": "diagnosed",
    "aufweisen": "exhibit",
    "aufweist": "exhibits",
    "aufwiesen": "exhibited",
    "kommen": "are considered",
    "kommt": "is considered",
    "benötigen": "require",
    "benötigt": "requires",
    "vorliegt": "is present",
    "vorliegen": "are present",
    "verlaufen": "progress",
    "verläuft": "progresses",
    "eingesetzt": "used",
    "einsetzen": "use",
    "einnehmen": "take",
    "eingenommen": "taken",
    "verabreicht": "administered",
    "verschrieben": "prescribed",
    "abgebrochen": "discontinued",
    "abgesetzt": "discontinued",
    "durchgeführt": "performed",
    "bestimmt": "determined",
    "festgestellt": "identified",
    "nachgewiesen": "demonstrated",
    "bestehen": "exist",
    "besteht": "exists",
    "führen": "lead",
    "führt": "leads",
    "zeigen": "show",
    "zeigt": "shows",
    "vorgesehen": "intended",
    "berücksichtigt": "considered",
    "definiert": "defined",
    "vorher": "previously",
    "bisher": "previously",
    "bedürfen": "require",
    "bedarf": "requires",
    "gegeben": "given",
    "begonnen": "initiated",
    "fortgesetzt": "continued",
    "gewechselt": "switched",
    "umgestellt": "switched",
    "übertragen": "transferred",
    "bewertet": "assessed",
    "untersucht": "investigated",
    "nachgewiesenen": "proven",
    "geprüft": "tested",
    "fehlgeschlagen": "failed",
    "versagt": "failed",

    # Medical nouns
    "Behandlung": "treatment",
    "Therapie": "therapy",
    "Therapien": "therapies",
    "Patienten": "patients",
    "Patientinnen": "patients",
    "Patient": "patient",
    "Erwachsene": "adults",
    "Erwachsenen": "adults",
    "Erwachsener": "adults",
    "erwachsenen": "adult",
    "erwachsener": "adult",
    "erwachsene": "adult",
    "Kinder": "children",
    "Kindern": "children",
    "Jugendliche": "adolescents",
    "Jugendlichen": "adolescents",
    "Frauen": "women",
    "Männern": "men",
    "Männer": "men",
    "Erkrankung": "disease",
    "Erkrankungen": "diseases",
    "Krankheit": "disease",
    "Infektionen": "infections",
    "Infektion": "infection",
    "Arzneimittel": "medicinal product",
    "Arzneimitteln": "medicinal products",
    "Tumor": "tumour",
    "Tumoren": "tumours",
    "Tumors": "tumour",
    "Krebs": "cancer",
    "Krebserkrankung": "cancer",
    "Karzinom": "carcinoma",
    "Karzinoms": "carcinoma",
    "Leukämie": "leukaemia",
    "Lymphom": "lymphoma",
    "Lymphoms": "lymphoma",
    "Sarkom": "sarcoma",
    "Risiko": "risk",
    "Symptome": "symptoms",
    "Symptomen": "symptoms",
    "Anzeichen": "signs",
    "Diagnose": "diagnosis",
    "Prognose": "prognosis",
    "Indikation": "indication",
    "Dosis": "dose",
    "Dosierung": "dosage",
    "Wirkung": "effect",
    "Wirksamkeit": "efficacy",
    "Nebenwirkungen": "side effects",
    "Sicherheit": "safety",
    "Monotherapie": "monotherapy",
    "Kombinationstherapie": "combination therapy",
    "Erstlinientherapie": "first-line therapy",
    "Zweitlinientherapie": "second-line therapy",
    "Erstlinienbehandlung": "first-line treatment",
    "Chemotherapie": "chemotherapy",
    "Immuntherapie": "immunotherapy",
    "Strahlentherapie": "radiotherapy",
    "Hormontherapie": "hormone therapy",
    "Stammzelltransplantation": "stem cell transplantation",
    "Transplantation": "transplantation",
    "Resektion": "resection",
    "Operation": "surgery",
    "Impfung": "vaccination",
    "Prophylaxe": "prophylaxis",
    "Prävention": "prevention",
    "Unverträglichkeit": "intolerance",
    "Überempfindlichkeit": "hypersensitivity",
    "Kontraindikation": "contraindication",
    "Blutdruck": "blood pressure",
    "Blutzucker": "blood sugar",
    "Blutzuckerkontrolle": "blood sugar control",
    "Blutgerinnung": "blood coagulation",
    "Blutplättchen": "platelets",
    "Blutung": "bleeding",
    "Blutungen": "bleedings",
    "Antikörper": "antibody",
    "Antikörpern": "antibodies",
    "Wirkstoff": "active substance",
    "Wirkstoffen": "active substances",
    "Wirkstoffe": "active substances",
    "Vortherapie": "prior therapy",
    "Vortherapien": "prior therapies",
    "Vorbehandlung": "prior treatment",
    "Nachbehandlung": "follow-up treatment",
    "Ansprechen": "response",
    "Ansprechrate": "response rate",
    "Überlebenszeit": "survival time",
    "Gesamtüberleben": "overall survival",
    "Überleben": "survival",
    "Lebensqualität": "quality of life",
    "Remission": "remission",
    "Remissionsdauer": "duration of remission",
    "Rezidiv": "relapse",
    "Progression": "progression",
    "Metastasierung": "metastasis",
    "Metastasen": "metastases",
    "Mortalität": "mortality",
    "Morbidität": "morbidity",
    "Inzidenz": "incidence",
    "Prävalenz": "prevalence",
    "Komorbidität": "comorbidity",
    "Komorbiditäten": "comorbidities",
    "Allgemeinzustands": "general condition",
    "Allgemeinzustand": "general condition",

    # Disease-specific
    "Lungenkarzinom": "lung cancer",
    "Brustkrebs": "breast cancer",
    "Melanom": "melanoma",
    "Melanoms": "melanoma",
    "Arthritis": "arthritis",
    "Asthma": "asthma",
    "Fibrose": "fibrosis",
    "Hepatitis": "hepatitis",
    "Pneumonie": "pneumonia",
    "Sepsis": "sepsis",
    "Anämie": "anaemia",
    "Thrombose": "thrombosis",
    "Embolie": "embolism",
    "Hypertonie": "hypertension",
    "Hypotonie": "hypotension",
    "Hypercholesterinämie": "hypercholesterolaemia",
    "Hyperlipidämie": "hyperlipidaemia",
    "Osteoporose": "osteoporosis",
    "Gicht": "gout",
    "Psoriasis": "psoriasis",
    "Dermatitis": "dermatitis",
    "Ekzem": "eczema",
    "Neurodermitis": "neurodermatitis",
    "Epilepsie": "epilepsy",
    "Schizophrenie": "schizophrenia",
    "Demenz": "dementia",
    "Splenomegalie": "splenomegaly",
    "Mastozytose": "mastocytosis",
    "Myelom": "myeloma",
    "Lymphknotenbeteiligung": "lymph node involvement",
    "Bluthochdruck": "high blood pressure",
    "Herzrhythmusstörungen": "cardiac arrhythmias",
    "Thrombozythämie": "thrombocythaemia",

    # Adjectives for disease
    "akuter": "acute",
    "akute": "acute",
    "akutem": "acute",
    "akuten": "acute",
    "chronischer": "chronic",
    "chronische": "chronic",
    "chronischem": "chronic",
    "chronischen": "chronic",
    "schwerer": "severe",
    "schwere": "severe",
    "schwerem": "severe",
    "schweren": "severe",
    "mittelschwerer": "moderate",
    "mittelschwere": "moderate",
    "mittelschweren": "moderate",
    "leichter": "mild",
    "leichte": "mild",
    "leichten": "mild",
    "mäßiger": "moderate",
    "mäßige": "moderate",
    "moderater": "moderate",
    "moderate": "moderate",
    "aktiver": "active",
    "aktive": "active",
    "aktivem": "active",
    "aktiven": "active",
    "primärer": "primary",
    "primäre": "primary",
    "primären": "primary",
    "sekundärer": "secondary",
    "sekundäre": "secondary",
    "sekundären": "secondary",
    "maligner": "malignant",
    "maligne": "malignant",
    "malignem": "malignant",
    "malignen": "malignant",
    "benigner": "benign",
    "benigne": "benign",
    "metastasiertem": "metastatic",
    "metastasierten": "metastatic",
    "metastasierte": "metastatic",
    "metastasierter": "metastatic",
    "rezidivierend": "relapsing",
    "rezidiviertem": "relapsed",
    "rezidivierenden": "relapsing",
    "rezidivierende": "relapsing",
    "refraktärem": "refractory",
    "refraktärer": "refractory",
    "refraktäre": "refractory",
    "rezidivierender": "relapsing",
    "systemischer": "systemic",
    "systemische": "systemic",
    "systemischem": "systemic",
    "systemischen": "systemic",
    "kutanem": "cutaneous",
    "kutanen": "cutaneous",
    "kutane": "cutaneous",
    "eosinophiler": "eosinophilic",
    "eosinophile": "eosinophilic",
    "idiopathischer": "idiopathic",
    "idiopathische": "idiopathic",
    "idiopathischem": "idiopathic",
    "idiopathischen": "idiopathic",
    "pädiatrischen": "paediatric",
    "pädiatrische": "paediatric",
    "hereditärer": "hereditary",
    "hereditäre": "hereditary",
    "hereditären": "hereditary",
    "kongenitaler": "congenital",
    "kongenitale": "congenital",
    "autosomal": "autosomal",
    "seltener": "rare",
    "seltene": "rare",
    "seltenen": "rare",
    "vorangegangene": "prior",
    "vorangegangenen": "prior",
    "vorangegangener": "prior",
    "vorherige": "prior",
    "vorheriger": "prior",
    "vorherigen": "prior",
    "vorhergehender": "prior",
    "vorhergehende": "prior",
    "bestimmter": "certain",
    "bestimmte": "certain",
    "bestimmten": "certain",
    "geringer": "low",
    "geringe": "low",
    "geringem": "low",
    "hoher": "high",
    "hohe": "high",
    "hohem": "high",
    "hohen": "high",
    "hohes": "high",
    "erhöhtem": "elevated",
    "erhöhter": "elevated",
    "erhöhte": "elevated",
    "erhöhten": "elevated",
    "niedrigem": "low",
    "niedriger": "lower",
    "niedrige": "low",
    "positiver": "positive",
    "positive": "positive",
    "positivem": "positive",
    "positiven": "positive",
    "negativer": "negative",
    "negative": "negative",
    "negativem": "negative",
    "negativen": "negative",
    "nachgewiesener": "proven",
    "nachgewiesene": "proven",
    "nachgewiesenem": "proven",
    "unzureichend": "inadequately",
    "ausreichend": "adequately",
    "vollständiger": "complete",
    "vollständige": "complete",
    "vollständig": "completely",
    "unvollständig": "incomplete",
    "abgeschlossener": "completed",
    "symptomatischer": "symptomatic",
    "symptomatische": "symptomatic",
    "symptomatischem": "symptomatic",
    "symptomatischen": "symptomatic",
    "asymptomatischer": "asymptomatic",
    "asymptomatische": "asymptomatic",
    "asymptomatischem": "asymptomatic",
    "progressiver": "progressive",
    "progressive": "progressive",
    "progressivem": "progressive",
    "progressiven": "progressive",
    "inoperablem": "inoperable",
    "inoperablen": "inoperable",
    "inoperabler": "inoperable",
    "inoperable": "inoperable",
    "operablem": "operable",
    "operable": "operable",
    "platinbasierter": "platinum-based",
    "platinbasierte": "platinum-based",
    "platinhaltiger": "platinum-containing",
    "platinhaltige": "platinum-containing",

    # Body parts / organs
    "Lunge": "lung",
    "Leber": "liver",
    "Niere": "kidney",
    "Nieren": "kidneys",
    "Herz": "heart",
    "Darm": "intestine",
    "Magen": "stomach",
    "Haut": "skin",
    "Blut": "blood",
    "Knochen": "bone",
    "Knochenmark": "bone marrow",
    "Gehirn": "brain",
    "Brust": "breast",
    "Prostata": "prostate",
    "Schilddrüse": "thyroid",
    "Lymphknoten": "lymph node",
    "Bauchspeicheldrüse": "pancreas",

    # Clinical terms
    "Übergang": "junction",
    "Übergangs": "junction",
    "Auswahl": "selection",
    "Maßgabe": "discretion",
    "ECOG": "ECOG",
    "PS": "PS",
    "Alter": "age",
    "Jahren": "years",
    "Monate": "months",
    "Monaten": "months",
    "Wochen": "weeks",
    "Tage": "days",
    "Tagen": "days",
    "kg": "kg",
    "mg": "mg",
    "Jahren": "years",
    "Jahre": "years",
    "Körpergewicht": "body weight",
    "Körpergewichts": "body weight",
    "Gewicht": "weight",
    "Bedarf": "need",
    "Dauer": "duration",
    "Umfang": "scope",
    "Versagen": "failure",
    "Abbruch": "discontinuation",
    "Zulassung": "authorisation",
    "Anwendung": "use",
    "Verordnung": "prescription",
    "Begleittherapie": "concomitant therapy",
    "Sauerstoffzufuhr": "oxygen supply",
    "Sauerstoffversorgung": "oxygen supply",
    "Sauerstoff": "oxygen",
    "Beatmung": "ventilation",
    "Akuttherapie": "acute therapy",
    "Akutbehandlung": "acute treatment",
    "Dauertherapie": "long-term therapy",
    "Langzeittherapie": "long-term therapy",
    "Erhaltungstherapie": "maintenance therapy",
    "Standardtherapie": "standard therapy",
    "Standardbehandlung": "standard treatment",
    "Systemtherapie": "systemic therapy",
    "Initialtherapie": "initial therapy",
    "Induktionstherapie": "induction therapy",
    "Konsolidierungstherapie": "consolidation therapy",
    "Salvagetherapie": "salvage therapy",
    "Zweitlinienbehandlung": "second-line treatment",
    "Drittlinientherapie": "third-line therapy",
    "Folgetherapie": "follow-up therapy",
    "Folgebehandlung": "follow-up treatment",
    "Kombinationschemotherapie": "combination chemotherapy",
    "Immunchemotherapie": "immunochemotherapy",
    "Radiochemotherapie": "radiochemotherapy",
    "Chemoradiotherapie": "chemoradiotherapy",
    "Radiotherapie": "radiotherapy",
    "Phototherapie": "phototherapy",
    "Gentherapie": "gene therapy",
    "Dialyse": "dialysis",
    "Hämodialyse": "haemodialysis",
    "Peritonealdialyse": "peritoneal dialysis",
    "Transfusion": "transfusion",
    "Transfusionen": "transfusions",
    "Kopfschmerzphase": "headache phase",
    "Kopfschmerz": "headache",
    "Schmerzen": "pain",
    "Schmerz": "pain",
    "Fieber": "fever",
    "Übelkeit": "nausea",
    "Erbrechen": "vomiting",
    "Durchfall": "diarrhoea",
    "Verstopfung": "constipation",
    "Müdigkeit": "fatigue",
    "Juckreiz": "pruritus",
    "Atemnot": "dyspnoea",
    "Husten": "cough",
    "Schwellung": "swelling",
    "Entzündung": "inflammation",
    "Infektion": "infection",
    "Exazerbation": "exacerbation",
    "Exazerbationen": "exacerbations",
    "Anfällen": "seizures",
    "Anfälle": "seizures",
    "Anfall": "seizure",
    "Schub": "relapse",
    "Schübe": "relapses",
    "Schüben": "relapses",
    "Attacken": "attacks",
    "Attacke": "attack",
    "Sulfonylharnstoff": "sulfonylurea",
    "Humaninsulin": "human insulin",
    "Insulin": "insulin",
    "Inhibitor": "inhibitor",
    "Inhibitoren": "inhibitors",
    "Rezeptor": "receptor",
    "Rezeptoren": "receptors",
    "Antikörpertherapie": "antibody therapy",
    "Genotyp": "genotype",
    "Genotypen": "genotypes",
    "Mutation": "mutation",
    "Mutationen": "mutations",
    "Expression": "expression",
    "Histologie": "histology",
    "Biomarker": "biomarker",
    "Surrogat": "surrogate",
    "Stadium": "stage",
    "Stadien": "stages",
    "Stadiums": "stage",
    "Grad": "grade",
    "Stufe": "level",
    "Stufen": "levels",
    "Schweregrad": "severity",
    "Schweregrads": "severity",
    "Schweregrade": "severities",
    "Klasse": "class",
    "Funktionsklasse": "functional class",
    "Klassifikation": "classification",
    "Einschlusskriterien": "inclusion criteria",
    "Kriterien": "criteria",
    "Kriterium": "criterion",
    "Zielpopulation": "target population",
    "Population": "population",
    "Subgruppe": "subgroup",
    "Subgruppen": "subgroups",
    "Subpopulation": "subpopulation",
    "Subpopulationen": "subpopulations",
    "Personengruppe": "group of persons",
    "Personen": "persons",
    "Altersgruppe": "age group",
    "Risikogruppe": "risk group",
    "Risikoprofil": "risk profile",
    "Risikofaktoren": "risk factors",
    "Risikofaktor": "risk factor",
    "Rahmen": "context",
    "Rahmens": "context",
    "Rahmenvertrag": "framework agreement",
    "Therapieintention": "treatment intent",
    "Therapielinie": "line of therapy",
    "Therapielinien": "lines of therapy",
    "Therapieregime": "therapy regimen",
    "Therapieversagen": "treatment failure",
    "Wirkstoffklasse": "drug class",
    "Wirkstoffgruppe": "drug class",
    "Darreichungsform": "dosage form",
    "Formulierung": "formulation",
    "Zulassungsstatus": "authorisation status",
    "Fachinformation": "summary of product characteristics",
    "Packungsbeilage": "package leaflet",
    "Kontrazeption": "contraception",
    "Schwangerschaft": "pregnancy",
    "Stillzeit": "breastfeeding",
    "Fruchtbarkeit": "fertility",
    "Lebenserwartung": "life expectancy",
    "Überlebensrate": "survival rate",
    "Ansprechraten": "response rates",
    "Krankheitsprogression": "disease progression",
    "Tumorprogression": "tumour progression",
    "Krankheitsaktivität": "disease activity",
    "Krankheitsverlauf": "disease course",
    "Krankheitsbild": "clinical picture",
    "Organfunktion": "organ function",
    "Nierenfunktion": "renal function",
    "Leberfunktion": "liver function",
    "Herzfunktion": "cardiac function",
    "Lungenfunktion": "lung function",
    "Nierenfunktionsstörung": "renal impairment",
    "Leberfunktionsstörung": "hepatic impairment",
    "Funktionsstörung": "dysfunction",
    "Organtransplantation": "organ transplantation",
    "Knochenmarktransplantation": "bone marrow transplantation",
    "Nierentransplantation": "kidney transplantation",
    "Lebertransplantation": "liver transplantation",
    "Herztransplantation": "heart transplantation",
    "Bluttransfusion": "blood transfusion",
    "Blutbildung": "haematopoiesis",
    "Gerinnungsfaktoren": "coagulation factors",

    # Adjectives/qualifiers frequently remaining
    "zusätzliche": "additional",
    "zusätzlicher": "additional",
    "zusätzlichen": "additional",
    "zusätzliches": "additional",
    "konventionelle": "conventional",
    "konventioneller": "conventional",
    "konventionellen": "conventional",
    "konventionellem": "conventional",
    "konventionelles": "conventional",
    "klassische": "classical",
    "klassischen": "classical",
    "typische": "typical",
    "typischen": "typical",
    "häufige": "common",
    "häufigen": "common",
    "seltener": "rare",
    "seltene": "rare",
    "seltenen": "rare",
    "bestimmter": "certain",
    "bestimmte": "certain",
    "bestimmten": "certain",
    "bekannter": "known",
    "bekannte": "known",
    "bekannten": "known",
    "humanen": "human",
    "humane": "human",
    "humanem": "human",
    "humaner": "human",
    "maximal": "maximum",
    "minimal": "minimum",
    "optimal": "optimal",
    "signifikant": "significant",
    "relevante": "relevant",
    "relevanten": "relevant",
    "relevanter": "relevant",
    "klinisch": "clinically",
    "klinische": "clinical",
    "klinischen": "clinical",
    "klinischer": "clinical",
    "klinischem": "clinical",
    "therapeutische": "therapeutic",
    "therapeutischen": "therapeutic",
    "therapeutischer": "therapeutic",
    "intravenös": "intravenously",
    "intravenöse": "intravenous",
    "intravenösen": "intravenous",
    "intravenöser": "intravenous",
    "subkutan": "subcutaneously",
    "subkutane": "subcutaneous",
    "subkutanen": "subcutaneous",
    "oral": "orally",
    "orale": "oral",
    "oralen": "oral",
    "oraler": "oral",
    "topisch": "topically",
    "topische": "topical",
    "topischen": "topical",
    "niedrig": "low",
    "niedrige": "low",
    "niedrigem": "low",
    "niedrigen": "low",
    "dosiertem": "dosed",
    "dosierte": "dosed",
    "dosierten": "dosed",
    "dosiert": "dosed",
    "hochdosiert": "high-dose",
    "hochdosierte": "high-dose",
    "hochdosierten": "high-dose",
    "transfusionsabhängiger": "transfusion-dependent",
    "transfusionsabhängige": "transfusion-dependent",
    "transfusionsabhängigen": "transfusion-dependent",
    "unkontrollierte": "uncontrolled",
    "unkontrollierten": "uncontrolled",
    "unkontrollierter": "uncontrolled",
    "unkontrolliertem": "uncontrolled",
    "heterozygot": "heterozygous",
    "heterozygote": "heterozygous",
    "heterozygoten": "heterozygous",
    "heterozygoter": "heterozygous",
    "homozygot": "homozygous",
    "homozygote": "homozygous",
    "homozygoten": "homozygous",
    "homozygoter": "homozygous",
    "lokoregionäre": "locoregional",
    "lokoregionärer": "locoregional",
    "lokoregionären": "locoregional",
    "bösartiger": "malignant",
    "bösartige": "malignant",
    "bösartigen": "malignant",
    "gutartige": "benign",
    "gutartiger": "benign",
    "gutartigen": "benign",
    "palliative": "palliative",
    "palliativer": "palliative",
    "palliativem": "palliative",
    "palliativ": "palliative",
    "kurative": "curative",
    "kurativer": "curative",
    "kurativem": "curative",
    "kurativ": "curative",
    "adjuvante": "adjuvant",
    "adjuvanter": "adjuvant",
    "adjuvantem": "adjuvant",
    "neoadjuvante": "neoadjuvant",
    "neoadjuvanter": "neoadjuvant",
    "neoadjuvantem": "neoadjuvant",
    "rezidivierendem": "relapsing",
    "vorbehandleten": "pretreated",
    "unbehandelter": "untreated",
    "unbehandelte": "untreated",
    "unbehandelten": "untreated",
    "unbehandeltem": "untreated",
    "vorbehandelter": "pretreated",
    "neudiagnostizierter": "newly diagnosed",
    "neudiagnostizierte": "newly diagnosed",
    "neudiagnostizierten": "newly diagnosed",
    "neudiagnostiziertem": "newly diagnosed",
    "neu": "newly",
    "folgenden": "following",
    "folgendem": "following",
    "folgender": "following",
    "folgende": "following",
    "ungünstigem": "unfavourable",
    "ungünstiger": "unfavourable",
    "ungünstige": "unfavourable",
    "ungünstigen": "unfavourable",
    "günstigem": "favourable",
    "günstiger": "favourable",
    "günstige": "favourable",
    "günstigen": "favourable",
    "angemessene": "appropriate",
    "angemessenen": "appropriate",
    "angemessener": "appropriate",
    "wesentliche": "essential",
    "wesentlichen": "essential",
    "allein": "alone",
    "alleine": "alone",

    # Misc medical compound words
    "Abhängigkeit": "dependency",
    "Stressauslöser": "stress inducer",
    "Vasodilatator": "vasodilator",
    "Bronchodilatator": "bronchodilator",
    "Thrombozytenaggregationshemmer": "platelet aggregation inhibitor",
    "Antikoagulanzien": "anticoagulants",
    "Antikoagulans": "anticoagulant",
    "Antikoagulation": "anticoagulation",
    "Thrombozytopenien": "thrombocytopenias",
    "Thrombozytopenie": "thrombocytopenia",
    "Neutropenie": "neutropenia",
    "Lymphopenie": "lymphopenia",
    "Leukopenie": "leucopenia",
    "Panzytopenie": "pancytopenia",
    "Immunmodulator": "immunomodulator",
    "immunmodulatorischen": "immunomodulatory",
    "immunmodulatorischer": "immunomodulatory",
    "immunmodulatorische": "immunomodulatory",
    "Immunsuppressivum": "immunosuppressant",
    "Immunsuppressiva": "immunosuppressants",
    "Kortikosteroide": "corticosteroids",
    "Kortikosteroid": "corticosteroid",
    "Kortikosteroiden": "corticosteroids",
    "Kortikoide": "corticoids",
    "Glukokortikoide": "glucocorticoids",
    "Glukokortikoid": "glucocorticoid",
    "Zytostatika": "cytostatic agents",
    "Zytostatikum": "cytostatic agent",
    "Antimetabolit": "antimetabolite",
    "Antimetaboliten": "antimetabolites",
    "Kinaseinhibitor": "kinase inhibitor",
    "Kinaseinhibitoren": "kinase inhibitors",
    "Tyrosinkinase": "tyrosine kinase",
    "Proteasom-Inhibitor": "proteasome inhibitor",
    "Proteasom-Inhibitoren": "proteasome inhibitors",
    "Checkpoint-Inhibitor": "checkpoint inhibitor",
    "Checkpoint-Inhibitoren": "checkpoint inhibitors",
    "monoklonaler": "monoclonal",
    "monoklonale": "monoclonal",
    "monoklonalen": "monoclonal",
    "monoklonales": "monoclonal",

    # G-BA specific
    "Zusatznutzen": "added benefit",
    "Nutzen": "benefit",
    "Schaden": "harm",
    "Evidenz": "evidence",
    "Beleg": "proof",
    "Hinweis": "indication",
    "Anhaltspunkt": "hint",
    "Aussagesicherheit": "evidence certainty",
    "Vergleichstherapie": "comparator therapy",
    "Festbetrag": "reference price",
    "Erstattungsbetrag": "reimbursement amount",
    "Nutzenbewertung": "benefit assessment",
}

# ── Sorted phrases by length (longest first) for greedy matching ─────

_SORTED_PHRASES = sorted(_PHRASES.keys(), key=len, reverse=True)


def translate_de_text(text: str) -> str:
    """Translate a German pharmaceutical/HTA text to English.

    Uses phrase-level matching first, then word-level fallback.
    Preserves drug names, abbreviations, and numbers as-is.
    """
    if not text or not text.strip():
        return text

    # Step 1: Apply phrase-level replacements (longest match first)
    result = text
    for phrase in _SORTED_PHRASES:
        if phrase in result:
            result = result.replace(phrase, _PHRASES[phrase])

    # Step 2: Apply word-level replacements for remaining German words
    # Split on whitespace but preserve separators
    tokens = re.split(r'(\s+)', result)
    translated_tokens = []
    for token in tokens:
        if not token or token.isspace():
            translated_tokens.append(token)
            continue

        # Strip punctuation for lookup, preserve it in output
        stripped = token.strip('.,;:()[]{}!?"""\'')
        prefix = token[:len(token) - len(token.lstrip('.,;:()[]{}!?"""\''))]
        suffix = token[len(stripped) + len(prefix):]

        if stripped in _WORDS:
            translated_tokens.append(prefix + _WORDS[stripped] + suffix)
        else:
            # Keep original (drug names, abbreviations, etc.)
            translated_tokens.append(token)

    return ''.join(translated_tokens)
